CREATE TABLE MEMBER(
    MEMBER_NO NUMBER, 
	MEMBER_ID VARCHAR2(20 BYTE) NOT NULL, 
	MEMBER_PW VARCHAR2(20 BYTE) NOT NULL, 
	MEMBER_NAME VARCHAR2(20 BYTE) NOT NULL, 
	MEMBER_PHONE VARCHAR2(20 BYTE) NOT NULL, 
	MEMBER_EMAIL VARCHAR2(20 BYTE) NOT NULL, 
	MEMBER_DATE DATE,
     CONSTRAINT MEMBER_pk PRIMARY KEY(MEMBER_NO)
   );
CREATE TABLE ENGINEER(
    ENGINEER_NO NUMBER, 
	ENGINNER_NAME VARCHAR2(20 BYTE) NOT NULL, 
	ENGINNER_PHONE VARCHAR2(20 BYTE) NOT NULL, 
	ENGINNER_EMAIL VARCHAR2(20 BYTE) NOT NULL, 
	ENGINNER_CAREER VARCHAR2(20 BYTE) NOT NULL, 
	ENGINNER_QUA VARCHAR2(20 BYTE) NOT NULL,
     CONSTRAINT ENGINEER PRIMARY KEY(ENGINEER_NO)
);
 CREATE TABLE CAR (
    CAR_NO NUMBER, 
	MEMBER_NO NUMBER REFERENCES MEMBER (MEMBER_NO), 
	CAR_NAME VARCHAR2(20 BYTE) NOT NULL, 
	CAR_MODEL VARCHAR2(20 BYTE) NOT NULL,
     CONSTRAINT CAR_pk PRIMARY KEY(CAR_NO)
   );
CREATE Table AUTO_MECHANIC(	
	MECHANIC_NO NUMBER, 
	CAR_NO NUMBER REFERENCES CAR (CAR_NO), 
	MECHANIC_SIT VARCHAR2(20 BYTE) NOT NULL, 
	MECHANIC_CONTENT VARCHAR2(20 BYTE) NOT NULL, 
	MECHANIC_DATE DATE,
    CONSTRAINT AUTO_MECHANIC_pk PRIMARY KEY(MECHANIC_NO)
);
CREATE TABLE MECHANIC_HISTORY(	
    HISTORY_NO NUMBER, 
	MEMBER_NO NUMBER  REFERENCES MEMBER (MEMBER_NO), 
	CAR_NO NUMBER  REFERENCES CAR (CAR_NO), 
	HISTORY_CONTENT VARCHAR2(20 BYTE) NOT NULL, 
	HISTORY_DATE DATE,
     CONSTRAINT MECHANIC_HISTORY_pk PRIMARY KEY(HISTORY_NO)
   );
